I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Capitulos/capitulo1.rpy", line 98, in script
    if noticia == 'F':
  File "game/Capitulos/capitulo1.rpy", line 98, in <module>
    if noticia == 'F':
NameError: name 'noticia' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Capitulos/capitulo1.rpy", line 98, in script
    if noticia == 'F':
  File "/home/nother/Games/renpy/renpy/ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "/home/nother/Games/renpy/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/nother/Games/renpy/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/Capitulos/capitulo1.rpy", line 98, in <module>
    if noticia == 'F':
NameError: name 'noticia' is not defined

Linux-6.13.8-zen1-1-zen-x86_64-with-glibc2.41 x86_64
Ren'Py 8.3.7.25031702
Espectral Promis 1.0
Sun Mar 30 21:58:51 2025
